const SIGNUP_URL = "https://mcwpromo.com/";
const TELEGRAM_URL = "https://t.me/bestplaybd_win_big";
function getSignupLink(brand) { return SIGNUP_URL; }
function currentLang() { return localStorage.getItem("bestplaybd_lang") || "bn"; }
function assetPath(src) { if (!src || /^(https?:)?\/\//.test(src) || src.startsWith("data:")) return src; return window.location.pathname.includes("/pages/") ? "../" + src : src; }
function applyLanguage(lang) { document.documentElement.lang = lang; document.querySelectorAll("[data-bn][data-en]").forEach(el => { el.textContent = el.getAttribute("data-" + lang); }); document.querySelectorAll(".lang-btn").forEach(btn => btn.classList.toggle("active", btn.dataset.lang === lang)); localStorage.setItem("bestplaybd_lang", lang); }
function applySignupLinks() { document.querySelectorAll("[data-signup-brand]").forEach(a => { a.href = getSignupLink(a.dataset.signupBrand || "MCW"); a.target = "_blank"; a.rel = "nofollow noopener"; }); document.querySelectorAll("[data-telegram-link]").forEach(a => { a.href = TELEGRAM_URL; a.target = "_blank"; a.rel = "nofollow noopener"; }); }
let promoDataCache = null;
async function loadPromoData() { if (promoDataCache) return promoDataCache; const path = window.location.pathname.includes("/pages/") ? "../data/promos.json" : "data/promos.json"; const res = await fetch(path, { cache: "no-store" }); if (!res.ok) throw new Error("Unable to load promo data"); promoDataCache = await res.json(); return promoDataCache; }
function walletLogosHTML() { return ["bKash","Nagad","Rocket","Upay","Bank"].map(name => '<span class="wallet-logo"><span class="wallet-mark">' + name.slice(0,2) + '</span><span class="wallet-name">' + name + '</span></span>').join(""); }
function enhanceWalletLogos() { document.querySelectorAll(".payment-grid:not(.payment-mini):not(.no-js-wallets)").forEach(grid => { grid.classList.add("logo-strip"); grid.innerHTML = walletLogosHTML(); }); }
function promoCardHTML(promo) { const lang = currentLang(); const title = promo["title_" + lang] || promo.title_en; const summary = promo["summary_" + lang] || promo.summary_en; const tag = promo["tag_" + lang] || promo.tag_en; return '<article class="card dynamic-promo-card"><img class="promo-banner" src="' + assetPath(promo.banner) + '" alt="' + title + '"><div class="promo-body"><div class="promo-meta"><span>' + promo.brand + '</span><span>' + tag + '</span></div><h3>' + title + '</h3><p class="promo-summary">' + summary + '</p><div class="promo-card-actions"><a class="btn btn-primary" href="' + getSignupLink(promo.brand) + '" data-signup-brand="' + promo.brand + '" target="_blank" rel="nofollow noopener">' + (lang === "bn" ? "বোনাস ক্লেইম করুন" : "Claim Bonus") + '</a></div></div></article>'; }
async function renderPromos() { const ids = ["promoSyncGrid", "featuredPromoGrid", "homePromoGrid"]; const mounts = ids.map(id => document.getElementById(id)).filter(Boolean); if (!mounts.length) return; try { const data = await loadPromoData(); mounts.forEach(mount => { const promos = mount.id === "featuredPromoGrid" ? data.promos.filter(p => p.featured).slice(0,5) : data.promos; mount.innerHTML = promos.map(promoCardHTML).join(""); mount.classList.add(mount.id === "featuredPromoGrid" ? "home-promo-showcase" : "promo-page-grid"); }); applySignupLinks(); } catch (e) { mounts.forEach(mount => { if (!mount.children.length) mount.innerHTML = '<article class="card empty-state"><h3>Promos loading</h3><p>Please refresh the page.</p></article>'; }); } }
document.addEventListener("DOMContentLoaded", () => { const saved = currentLang(); applyLanguage(saved); applySignupLinks(); enhanceWalletLogos(); renderPromos(); const menuToggle = document.getElementById("menuToggle"); const mainNav = document.getElementById("mainNav"); if (menuToggle && mainNav) menuToggle.addEventListener("click", () => mainNav.classList.toggle("show")); document.querySelectorAll(".lang-btn").forEach(btn => btn.addEventListener("click", () => { applyLanguage(btn.dataset.lang); renderPromos(); })); });
